### PR TITLE
Attempt at bumping forester to release 4.2

### LINKED ISSUE #99: Upgrade forester in CI for v4.2 release
Following up #71, forester [v4.2](http://www.jonmsterling.com/jms-00WK.xml) *is* now officially released on OPAM. The build script used in the CI should be updated accordingly; it currently references the v4.2 pre-release.

### PR DESCRIPTION
**Pull request by TheCedarPrince**
# Default TODO list

- [ ] Are all notable changes added to the changelog in `dev-docs/`?
- [x] Are there any manual checks that you did while preparing this release that could be automated and become part of the CI?
- [x] Are any relevant issues to the PR mentioned so that they will be automatically closed when the PR merges?

# Purpose

This attempts to fix #99 by bumping the forester release tarball and linking to the established archive page now that Owen and Jon got binary building working per: https://lists.sr.ht/~jonsterling/forester-devel/patches/54175#%3C87cymw2ejz.fsf@owenlynch.org%3E+static.patch

Let me know if anything else is needed here! :smile: 

P.S. I could not find a changelog in dev-docs so this bump has not been recorded.

### CODE REVIEW

**Comment by TheCedarPrince** [comment]
So this works temporarily for specifically 4.2 using Docker but obviously that is quite a heavy dependency but I don't know a better way at the moment of managing specifically 4.2 because Forester does not have a Dockerfile set-up until 4.3 officially thanks to the patch from Owen. I know Owen was suggesting hosting the build somewhere but I am not too sure what else to do here.

**Comment by epatters** [comment]
Thanks a lot Jacob for undertaking this!

@olynch, as our resident forester expert, can  you please review this PR when you have a moment?

**Comment by olynch** [comment]
We definitely should not be running docker in CI. @TheCedarPrince any easy place to upload things is https://web3.storage, which is what I originally did. If you want to build the binary and upload there that would be great.

**Comment by TheCedarPrince** [comment]
Hey @olynch and @epatters,

I created a repository here: https://github.com/TheCedarPrince/ForesterBuilds that stores Forester builds for the moment. I updated the PR to not use Docker and pulls down a built tarball just fine now. How does that look?

P.S. I apologize for not using web3.storage but it was asking for my credit card and I was a bit hesitant to sign-up. If you want to just pull binaries from there and upload to your web3 account, that might be best since that would be under Topos Inst. control too.

**Comment by olynch** [comment]
Looks great! Thanks @TheCedarPrince!

**Comment by TheCedarPrince** [comment]
You got it @olynch! I'm on the Forester mailing list so when I see a new release made, I'll build a new binary for patching.

**Comment by epatters** [comment]
Thank you both, @TheCedarPrince and @olynch!

**Pull request merged**
